chain:
  # -- Internal: name of the testnet to connect to
  name: testnet
  # -- Bump this number to wipe the underlying storage
  era: 1
  # -- Aptos Chain ID
  chain_id: 4
  # -- If specified, the root key for the testnet
  root_key: '0x5243ca72b0766d9e9cbf2debf6153443b01a1e0e6d086c7ea206eaf6f8043956'
  min_stake: 0
  max_stake: 100000
  min_lockup_duration_secs: 0
  max_lockup_duration_secs: 2592000 # 1 month
  epoch_duration_secs: 86400 # 1 day
  # instead of specifying "initial_lockup_timestamp", just take the delta between
  # the current timestamp
  initial_lockup_duration: 1d
  min_price_per_gas_unit: 1
  allow_new_validators: false

# -- Default image tag to use for all tools images
imageTag: testnet

genesis:
  image:
    # -- Image repo to use for tools image for running genesis
    repo: aptoslabs/tools
    # -- Image tag to use for tools image. If set, overrides `imageTag`
    tag:
    # -- Image pull policy to use for tools image
    pullPolicy: IfNotPresent
  # -- Number of validators to include in genesis
  numValidators: 1
  # -- If `enable_onchain_discovery` is false, use this kubernetes service name prefix. It should be the fullname for the aptos-node helm release
  username_prefix: aptos-node
  # -- If set, the base domain name of the fullnode and validator endpoints
  domain:
  validator:
    # -- Use External DNS as created by aptos-node helm chart for validator host in genesis
    enable_onchain_discovery: false
    # -- If `enable_onchain_discovery` is false, use this host suffix for internal kubernetes service name
    internal_host_suffix: validator-lb
  fullnode:
    # -- Use External DNS as created by aptos-node helm chart for fullnode host in genesis
    enable_onchain_discovery: true
    # -- If `enable_onchain_discovery` is false, use this host suffix for internal kubernetes service name
    internal_host_suffix: fullnode-lb
  # -- The local path for move modules in the docker image. Defaults to the aptos-framework in the aptoslabs/tools docker image
  moveModulesDir: /aptos-framework/move/modules

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name:

# -- LEGACY: create PodSecurityPolicy, which exists at the cluster-level
podSecurityPolicy: true
